language: python


matrix:
  include:
    - python: "2.6"
      env: TOX_ENV=py26
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "pypy-5.3.1"
      env: TOX_ENV=pypy
    - python: "2.7"
      env: TOX_ENV=flake8
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36


install:
    - pip install tox


script:
  - tox -e $TOX_ENV
